#ifndef __includefiles_h__
#define __includefiles_h__
#define D3D10_IGNORE_SDK_LAYERS
#include <windows.h>
#include <tchar.h>
#include <stdio.h>
//#include <d3dcsx.h>
//#include <D3d10shader.h>
#include "Globals.h"
#include "basics.h"
#include "engine.h"
#include "Fonts.h"
#pragma comment(lib,"d3dx9.lib")
#pragma comment(lib,"d3d9")
#include <stdio.h>
#include <d3d10.h>
#include <d3d9.h>
#include <d3dx9tex.h>
#endif